import React, { useState, useRef, useEffect } from 'react';
import { Send, Paperclip, X, FileText } from 'lucide-react';
import { useChat } from '../hooks/useChat';

export default function MessageInput() {
  const { sendMessage, loading, selectedProvider } = useChat();
  const [text, setText] = useState('');
  const [attachedFile, setAttachedFile] = useState(null);
  const textareaRef = useRef(null);
  const fileInputRef = useRef(null);

  // Auto resize textarea height
  useEffect(() => {
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto';
      textareaRef.current.style.height = `${Math.min(textareaRef.current.scrollHeight, 180)}px`;
    }
  }, [text]);

  const handleSend = () => {
    if ((!text.trim() && !attachedFile) || loading) return;

    let fullMessage = text.trim();
    if (attachedFile) {
      fullMessage = `[Attached File: ${attachedFile.name}]\n${fullMessage}`;
    }

    sendMessage(fullMessage);
    setText('');
    setAttachedFile(null);
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto';
    }
  };

  const handleKeyDown = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const handleFileChange = (e) => {
    const file = e.target.files?.[0];
    if (file) {
      setAttachedFile(file);
    }
    e.target.value = '';
  };

  return (
    <div className="p-4 bg-white/95 backdrop-blur-md border-t border-gray-200">
      <div className="max-w-4xl mx-auto">
        {/* Attached file preview chip */}
        {attachedFile && (
          <div className="mb-2 flex items-center gap-2 bg-blue-50 border border-blue-200 text-blue-800 text-xs px-3 py-1.5 rounded-lg w-fit">
            <FileText className="w-3.5 h-3.5 text-blue-600" />
            <span className="font-medium truncate max-w-xs">{attachedFile.name}</span>
            <span className="text-blue-500 text-[10px]">({Math.round(attachedFile.size / 1024)} KB)</span>
            <button
              onClick={() => setAttachedFile(null)}
              className="text-blue-400 hover:text-blue-700 ml-1"
            >
              <X className="w-3.5 h-3.5" />
            </button>
          </div>
        )}

        {/* Input box */}
        <div className="relative flex items-end gap-2 bg-gray-50 border border-gray-200 rounded-2xl p-2 focus-within:bg-white focus-within:border-blue-500 focus-within:ring-2 focus-within:ring-blue-500/20 transition-all shadow-2xs">
          {/* File Attachment Button */}
          <input
            type="file"
            ref={fileInputRef}
            onChange={handleFileChange}
            className="hidden"
            accept=".txt,.md,.json,.js,.py,.html,.css,.csv"
          />
          <button
            type="button"
            onClick={() => fileInputRef.current?.click()}
            className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-200/60 rounded-xl transition-colors shrink-0"
            title="Attach a text or code document"
          >
            <Paperclip className="w-5 h-5" />
          </button>

          {/* Textarea */}
          <textarea
            ref={textareaRef}
            rows={1}
            value={text}
            onChange={(e) => setText(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder={`Message ${selectedProvider === 'openrouter' ? 'OpenRouter' : selectedProvider === 'huggingface' ? 'Hugging Face' : 'Botpress'}...`}
            className="w-full resize-none bg-transparent py-1.5 px-2 text-sm sm:text-base text-gray-900 placeholder:text-gray-400 focus:outline-none max-h-44 leading-relaxed"
          />

          {/* Send Button */}
          <button
            type="button"
            onClick={handleSend}
            disabled={(!text.trim() && !attachedFile) || loading}
            className="p-2.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white disabled:bg-gray-200 disabled:text-gray-400 disabled:cursor-not-allowed transition-all shrink-0 shadow-2xs"
            title="Send message (Enter)"
          >
            <Send className="w-4 h-4" />
          </button>
        </div>

        {/* Footnote */}
        <div className="flex items-center justify-between mt-2 px-2 text-[11px] text-gray-400">
          <span>Press <kbd className="px-1.5 py-0.5 bg-gray-100 rounded border border-gray-200 font-mono text-[10px] text-gray-600">Enter</kbd> to send, <kbd className="px-1.5 py-0.5 bg-gray-100 rounded border border-gray-200 font-mono text-[10px] text-gray-600">Shift + Enter</kbd> for new line</span>
          <span className="hidden sm:inline">Responses are generated by real configured AI providers</span>
        </div>
      </div>
    </div>
  );
}
